<script setup lang="ts">
import { ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { http } from '@/utils/request'
const merchantId=ref(''), items=ref<any[]>([]), quote=ref<any>(null), coupons=ref<any[]>([]), selectedCouponId=ref(''), address=ref(''), phone=ref(''), remark=ref(''), saving=ref(false)
const payload=(v:any)=>v?.data?.data??v?.data??v??{}
const optionText=(item:any)=>Array.isArray(item?.selected_options)?item.selected_options.map((option:any)=>`${option.group_name}:${option.choice_name}`).join(' · '):''
async function loadQuote(){try{quote.value=payload(await http.post('/food/orders/quote',{merchant_id:merchantId.value,items:items.value,user_coupon_id:selectedCouponId.value||undefined})).quote}catch(e:any){if(selectedCouponId.value){selectedCouponId.value='';return loadQuote()}uni.showToast({title:e?.message||'订单信息已变化',icon:'none'})}}
async function load(){await loadQuote();try{const data=payload(await http.get('/coupons/usable',{amount:quote.value?.total_amount||0}));coupons.value=Array.isArray(data)?data:(data.list||[])}catch{coupons.value=[]}}
function selectCoupon(id:string){selectedCouponId.value=selectedCouponId.value===id?'':id;void loadQuote()}
async function submit(){if(!address.value.trim())return uni.showToast({title:'请填写收餐地点',icon:'none'});if(saving.value)return;saving.value=true;try{const created=payload(await http.post('/food/orders',{merchant_id:merchantId.value,items:items.value,user_coupon_id:selectedCouponId.value||undefined,delivery_address:address.value,contact_phone:phone.value,remark:remark.value})).order;const paid=payload(await http.post(`/food/orders/${created.id}/pay`,{})).order;uni.showToast({title:'支付成功',icon:'success'});setTimeout(()=>uni.redirectTo({url:`/pages/food/detail?id=${paid.id}`}),550)}catch(e:any){uni.showToast({title:e?.message||'下单失败',icon:'none'})}finally{saving.value=false}}
onLoad((q:any)=>{merchantId.value=String(q.merchant||'');try{items.value=JSON.parse(decodeURIComponent(String(q.items||'[]')))}catch{items.value=[]}void load()})
</script>
<template><view class="checkout"><view v-if="!quote" class="state">正在核算订单…</view><template v-else><view class="card"><text class="heading">收餐信息</text><input v-model="address" placeholder="例如：北区 3 栋 402"/><input v-model="phone" placeholder="联系电话（选填）"/></view><view class="card"><text class="heading">{{quote.merchant?.name}}</text><view v-for="item in quote.items" :key="item.id" class="line"><view><text>{{item.name}} × {{item.quantity}}</text><text v-if="optionText(item)" class="option-text">{{optionText(item)}}</text></view><text>¥{{(item.price*item.quantity).toFixed(2)}}</text></view><textarea v-model="remark" maxlength="500" placeholder="口味、餐具等备注（选填）"/></view><view v-if="coupons.length" class="card"><text class="heading">可用优惠券</text><view v-for="row in coupons" :key="row.id" class="line" :style="selectedCouponId===row.id?'color:#299566;font-weight:700':''" @tap="selectCoupon(row.id)"><text>{{row.coupon?.name||'优惠券'}}</text><text>{{selectedCouponId===row.id?'已选择':'选择'}}</text></view></view><view class="card"><view class="line"><text>餐品小计</text><text>¥{{Number(quote.item_amount).toFixed(2)}}</text></view><view class="line"><text>配送费</text><text>¥{{Number(quote.delivery_fee).toFixed(2)}}</text></view><view v-if="Number(quote.discount_amount)>0" class="line" style="color:#d35b4a"><text>优惠</text><text>-¥{{Number(quote.discount_amount).toFixed(2)}}</text></view><view class="total"><text>合计（钱包支付）</text><text>¥{{Number(quote.payable_amount||quote.total_amount).toFixed(2)}}</text></view></view><view class="bar"><view><text>应付 </text><text class="money">¥{{Number(quote.payable_amount||quote.total_amount).toFixed(2)}}</text></view><button :loading="saving" @tap="submit">确认支付</button></view></template></view></template>
<style scoped lang="scss">.checkout{min-height:100vh;padding:22rpx 22rpx 132rpx;background:#f6f9f3}.state{padding-top:140rpx;text-align:center;color:#819087}.card{display:grid;gap:20rpx;margin-bottom:18rpx;padding:26rpx;border-radius:24rpx;background:#fff}.heading{color:#26392f;font-size:30rpx;font-weight:750}.card input,.card textarea{padding:18rpx 0;border-bottom:1rpx solid #edf1ee;font-size:26rpx}.card textarea{width:100%;height:100rpx}.line,.total{display:flex;justify-content:space-between;font-size:25rpx}.line text:last-child{font-weight:650}.option-text{display:block;margin-top:5rpx;color:#6d8778;font-size:20rpx;font-weight:400}.total{padding-top:20rpx;border-top:1rpx solid #edf1ee;font-weight:750}.total text:last-child,.money{color:#e76843;font-size:33rpx}.bar{position:fixed;right:0;bottom:0;left:0;display:flex;height:108rpx;padding:0 24rpx;align-items:center;justify-content:space-between;background:#fff;box-shadow:0 -4rpx 18rpx rgba(35,65,43,.08)}.bar button{margin:0;border-radius:36rpx;background:#52c41a;color:#fff;font-size:27rpx}</style>
