<script setup lang="ts">
import { ref } from 'vue'
import { onLoad, onPullDownRefresh } from '@dcloudio/uni-app'
import { http } from '@/utils/request'
const order=ref<any>(null),loading=ref(false),id=ref('');const payload=(v:any)=>v?.data?.data??v?.data??v??{}
const label=(v:string)=>({PENDING_PAYMENT:'等待支付',PAID:'等待商家接单',MERCHANT_ACCEPTED:'商家已接单',PREPARING:'餐品制作中',READY_FOR_PICKUP:'等待跑腿员取餐',ACCEPTED:'跑腿员已接单',PICKED:'跑腿员已取餐',DELIVERING:'正在配送',DELIVERED:'已送达，等待确认',COMPLETED:'订单已完成',CANCELLED:'订单已取消',REFUNDED:'已退款'}as any)[v]||v
const optionText=(item:any)=>Array.isArray(item?.selected_options)?item.selected_options.map((option:any)=>`${option.group_name}:${option.choice_name}`).join(' · '):''
async function load(){loading.value=true;try{order.value=payload(await http.get(`/food/orders/${id.value}`)).order}catch(e:any){uni.showToast({title:e?.message||'订单加载失败',icon:'none'})}finally{loading.value=false;uni.stopPullDownRefresh()}}
async function action(name:string){try{const result=payload(await http.post(`/food/orders/${id.value}/${name}`,{}));order.value=result.order;uni.showToast({title:name==='confirm'?'已确认收餐':'已取消',icon:'success'})}catch(e:any){uni.showToast({title:e?.message||'操作失败',icon:'none'})}}
onLoad((q:any)=>{id.value=String(q.id||'');load()});onPullDownRefresh(load)
</script>
<template><view class="detail"><view v-if="loading&&!order" class="state">订单加载中…</view><template v-else-if="order"><view class="hero"><text>{{label(order.status)}}</text><text>{{order.merchant?.name}} · 订单 {{order.order_no||`#${order.id}`}}</text></view><view class="card"><text class="heading">配送信息</text><text class="address">{{order.delivery_address}}</text><text class="muted">{{order.contact_phone||'未填写联系电话'}}</text><text v-if="order.pickup_code" class="code">取餐码 {{order.pickup_code}}</text></view><view class="card"><text class="heading">餐品明细</text><view v-for="item in order.items" :key="item.id" class="line"><view><text>{{item.item_name}} × {{item.quantity}}</text><text v-if="optionText(item)" class="option-text">{{optionText(item)}}</text></view><text>¥{{(item.unit_price*item.quantity).toFixed(2)}}</text></view><view class="line"><text>配送费</text><text>¥{{Number(order.delivery_fee).toFixed(2)}}</text></view><view class="total">实付 ¥{{Number(order.payable_amount||order.total_amount).toFixed(2)}}</view></view><view class="card"><text class="heading">订单进度</text><view v-for="step in order.timeline" :key="step.id" class="timeline"><view></view><text>{{label(step.to_status)}}<small>{{new Date(step.created_at).toLocaleString('zh-CN',{hour12:false})}}</small></text></view></view><view v-if="order.status==='DELIVERED'||order.status==='PAID'||order.status==='PENDING_PAYMENT'" class="bar"><button v-if="order.status==='DELIVERED'" @tap="action('confirm')">确认收餐</button><button v-else @tap="action('cancel')">取消订单</button></view></template></view></template>
<style scoped lang="scss">.detail{min-height:100vh;padding-bottom:120rpx;background:#f6f9f3}.state{padding-top:160rpx;text-align:center;color:#849087}.hero{display:grid;gap:10rpx;padding:38rpx 32rpx;background:linear-gradient(135deg,#226e46,#65bd8a);color:#eafff0}.hero text:first-child{font-size:39rpx;font-weight:800}.hero text:last-child{font-size:22rpx;opacity:.85}.card{display:grid;gap:18rpx;margin:20rpx 22rpx;padding:26rpx;border-radius:23rpx;background:#fff}.heading{font-size:29rpx;font-weight:750}.address{font-size:27rpx}.muted{color:#849087;font-size:22rpx}.code{padding:14rpx;border-radius:12rpx;background:#effaf2;color:#338f62;font-size:28rpx;font-weight:700}.line{display:flex;justify-content:space-between;color:#59675f;font-size:24rpx}.option-text{display:block;margin-top:5rpx;color:#6d8778;font-size:20rpx}.total{padding-top:16rpx;border-top:1rpx solid #edf1ee;color:#e76843;font-size:30rpx;font-weight:800;text-align:right}.timeline{display:flex;gap:16rpx;align-items:start}.timeline view{width:14rpx;height:14rpx;margin-top:8rpx;border-radius:50%;background:#52c41a}.timeline text{font-size:24rpx}.timeline small{display:block;margin-top:5rpx;color:#99a39d;font-size:20rpx}.bar{position:fixed;right:0;bottom:0;left:0;padding:18rpx 24rpx;background:#fff}.bar button{border-radius:36rpx;background:#52c41a;color:#fff}</style>
