<script setup lang="ts">
import { computed, ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { http } from '@/utils/request'
type Item={id:number;name:string;description?:string;image?:string;price:number;original_price?:number;stock:number;category_id?:number}
type Category={id:number;name:string}
const merchant=ref<any>(null), items=ref<Item[]>([]), categories=ref<Category[]>([]), active=ref<number|undefined>(), loading=ref(false), cart=ref<Record<number,number>>({})
const payload=(v:any)=>v?.data?.data??v?.data??v??{}
const shown=computed(()=>active.value?items.value.filter(v=>v.category_id===active.value):items.value)
const count=computed(()=>Object.values(cart.value).reduce((a,b)=>a+b,0)); const amount=computed(()=>items.value.reduce((a,v)=>a+v.price*(cart.value[v.id]||0),0))
async function load(id:string){loading.value=true;try{const data=payload(await http.get(`/food/merchants/${id}`)); merchant.value=data.merchant;items.value=data.menu_items||[];categories.value=data.categories||[];active.value=categories.value[0]?.id}catch(e:any){uni.showToast({title:e?.message||'菜单加载失败',icon:'none'})}finally{loading.value=false}}
function add(item:Item,delta:number){const next=Math.max(0,(cart.value[item.id]||0)+delta);if(item.stock>=0&&next>item.stock)return uni.showToast({title:'库存不足',icon:'none'});cart.value={...cart.value,[item.id]:next}}
function checkout(){const selected=items.value.filter(v=>cart.value[v.id]).map(v=>({id:v.id,quantity:cart.value[v.id]}));if(!selected.length)return;uni.navigateTo({url:`/pages/food/checkout?merchant=${merchant.value.id}&items=${encodeURIComponent(JSON.stringify(selected))}`})}
onLoad((q:any)=>load(String(q.id||'')))
</script>
<template><view class="menu-page"><view v-if="loading" class="state">菜单加载中…</view><template v-else-if="merchant"><view class="store"><text class="title">{{merchant.name}}</text><text>{{merchant.announcement||merchant.description||merchant.address}}</text><view><text>起送 ¥{{Number(merchant.min_order_amount||0).toFixed(0)}}</text><text>{{merchant.prepare_minutes||15}} 分钟备餐</text></view></view><view class="content"><scroll-view scroll-y class="cats"><view :class="{active:!active}" @tap="active=undefined">全部</view><view v-for="c in categories" :key="c.id" :class="{active:active===c.id}" @tap="active=c.id">{{c.name}}</view></scroll-view><scroll-view scroll-y class="foods"><view v-if="!shown.length" class="empty">该分类暂无菜品</view><view v-for="item in shown" :key="item.id" class="food"><image v-if="item.image" :src="item.image" mode="aspectFill"/><view v-else class="food-img">餐</view><view class="info"><text class="name">{{item.name}}</text><text class="desc">{{item.description||'新鲜现做'}}</text><text class="stock" v-if="item.stock>=0">余 {{item.stock}}</text><view class="bottom"><view><text class="price">¥{{Number(item.price).toFixed(2)}}</text><text v-if="item.original_price" class="old">¥{{Number(item.original_price).toFixed(2)}}</text></view><view class="step"><text v-if="cart[item.id]" @tap="add(item,-1)">−</text><text v-if="cart[item.id]" class="num">{{cart[item.id]}}</text><text @tap="add(item,1)">＋</text></view></view></view></view></scroll-view></view><view class="cart"><view><text class="dot">{{count}}</text><text>¥{{amount.toFixed(2)}}</text><text class="fee">另需配送费</text></view><button :disabled="!count" @tap="checkout">去结算</button></view></template></view></template>
<style scoped lang="scss">.menu-page{min-height:100vh;padding-bottom:132rpx;background:#f6f9f3}.state,.empty{padding:80rpx 20rpx;text-align:center;color:#849087}.store{padding:30rpx 32rpx;background:#fff;color:#748078;font-size:23rpx}.store .title{display:block;margin-bottom:12rpx;color:#26392f;font-size:38rpx;font-weight:800}.store view{display:flex;gap:22rpx;margin-top:15rpx;color:#4ba475;font-size:21rpx}.content{display:flex;height:calc(100vh - 255rpx)}.cats{width:172rpx;background:#eef4ef}.cats view{padding:28rpx 14rpx;text-align:center;color:#64746b;font-size:24rpx}.cats view.active{background:#fff;color:#2d8c61;font-weight:700}.foods{flex:1;padding:18rpx 18rpx;background:#fff}.food{display:flex;gap:16rpx;padding:18rpx 0;border-bottom:1rpx solid #edf1ee}.food image,.food-img{width:132rpx;height:132rpx;flex:0 0 auto;border-radius:15rpx}.food-img{display:flex;align-items:center;justify-content:center;background:#e6f5eb;color:#5ab484;font-size:35rpx}.info{display:flex;min-width:0;flex:1;flex-direction:column}.name{font-size:28rpx;font-weight:700}.desc,.stock{overflow:hidden;margin-top:8rpx;color:#8a958f;font-size:21rpx;text-overflow:ellipsis;white-space:nowrap}.bottom{display:flex;margin-top:auto;align-items:end;justify-content:space-between}.price{color:#e76843;font-size:29rpx;font-weight:800}.old{margin-left:6rpx;color:#a1aba5;font-size:19rpx;text-decoration:line-through}.step{display:flex;align-items:center;gap:12rpx;color:#279761;font-size:35rpx;font-weight:600}.num{min-width:20rpx;color:#26392f;font-size:25rpx;text-align:center}.cart{position:fixed;z-index:3;right:20rpx;bottom:18rpx;left:20rpx;display:flex;height:92rpx;padding-left:27rpx;align-items:center;justify-content:space-between;border-radius:48rpx;background:#263c30;color:#fff;box-shadow:0 10rpx 28rpx rgba(19,51,32,.24)}.dot{display:inline-flex;min-width:30rpx;height:30rpx;margin-right:10rpx;align-items:center;justify-content:center;border-radius:20rpx;background:#55bf7e;font-size:18rpx}.fee{margin-left:15rpx;color:#bdc9c0;font-size:19rpx}.cart button{height:92rpx;margin:0;padding:0 38rpx;border:0;border-radius:48rpx;background:#52c41a;color:#fff;font-size:27rpx}.cart button[disabled]{background:#8c9b91}</style>
