<script setup lang="ts">
import { ref } from 'vue'
import { onLoad, onPullDownRefresh, onShow } from '@dcloudio/uni-app'
import { http } from '@/utils/request'
const orders=ref<any[]>([]),loading=ref(false);const payload=(v:any)=>v?.data?.data??v?.data??v??{}
const status=(v:string)=>({PENDING_PAYMENT:'待支付',PAID:'待商家接单',MERCHANT_ACCEPTED:'商家已接单',PREPARING:'正在备餐',READY_FOR_PICKUP:'等待取餐',ACCEPTED:'跑腿员已接单',PICKED:'已取餐',DELIVERING:'配送中',DELIVERED:'已送达',COMPLETED:'已完成',CANCELLED:'已取消',REFUNDED:'已退款'}as any)[v]||v
async function load(){loading.value=true;try{const d=payload(await http.get('/food/orders/my',{page:1,page_size:50}));orders.value=d.list||[]}catch(e:any){uni.showToast({title:e?.message||'订单加载失败',icon:'none'})}finally{loading.value=false;uni.stopPullDownRefresh()}}function open(id:number){uni.navigateTo({url:`/pages/food/detail?id=${id}`})}onLoad(load);onShow(load);onPullDownRefresh(load)
</script>
<template><view class="orders"><view v-if="loading" class="state">正在加载订单…</view><view v-else-if="!orders.length" class="state">暂无外卖订单<button size="mini" @tap="()=>uni.redirectTo({url:'/pages/food/index'})">去点餐</button></view><view v-else v-for="order in orders" :key="order.id" class="order" @tap="open(order.id)"><view class="head"><text>{{order.merchant?.name||'校园商家'}}</text><text class="badge">{{status(order.status)}}</text></view><view class="items">{{order.items.map((v:any)=>`${v.item_name} ×${v.quantity}`).join('、')}}</view><view class="foot"><text>{{new Date(order.created_at).toLocaleString('zh-CN',{hour12:false})}}</text><text>实付 ¥{{Number(order.payable_amount||order.total_amount).toFixed(2)}} ›</text></view></view></view></template>
<style scoped lang="scss">.orders{min-height:100vh;padding:22rpx;background:#f6f9f3}.state{display:flex;min-height:360rpx;align-items:center;justify-content:center;flex-direction:column;gap:22rpx;color:#839087}.state button{margin:0;border-radius:30rpx;background:#52c41a;color:#fff}.order{margin-bottom:18rpx;padding:25rpx;border-radius:24rpx;background:#fff}.head,.foot{display:flex;justify-content:space-between;align-items:center}.head text:first-child{font-size:29rpx;font-weight:750}.badge{padding:6rpx 12rpx;border-radius:10rpx;background:#e8f7ed;color:#2e9763;font-size:21rpx}.items{overflow:hidden;margin:19rpx 0;color:#59675f;font-size:24rpx;text-overflow:ellipsis;white-space:nowrap}.foot{padding-top:18rpx;border-top:1rpx solid #edf1ee;color:#8b958f;font-size:21rpx}.foot text:last-child{color:#26392f;font-size:26rpx}</style>
