<script setup lang="ts">
import { ref } from 'vue'
import { onLoad, onPullDownRefresh } from '@dcloudio/uni-app'
import { http } from '@/utils/request'
const tab=ref<'available'|'mine'>('available'),orders=ref<any[]>([]),loading=ref(false);const payload=(v:any)=>v?.data?.data??v?.data??v??{}
const text=(s:string)=>({READY_FOR_PICKUP:'待取餐',ACCEPTED:'待取餐',PICKED:'已取餐',DELIVERING:'配送中',DELIVERED:'等待用户确认',COMPLETED:'已完成'}as any)[s]||s
async function load(){loading.value=true;try{const d=payload(await http.get('/food/runner/orders',{available:tab.value==='available',page:1,page_size:50}));orders.value=d.list||[]}catch(e:any){uni.showToast({title:e?.message||'配送单加载失败',icon:'none'})}finally{loading.value=false;uni.stopPullDownRefresh()}}
async function doAction(order:any,action:string){try{if(action==='accept')await http.post(`/food/runner/orders/${order.id}/accept`,{});else await http.post(`/food/runner/orders/${order.id}/status`,{action});uni.showToast({title:'操作成功',icon:'success'});load()}catch(e:any){uni.showToast({title:e?.message||'操作失败',icon:'none'})}}
function next(s:string){return s==='ACCEPTED'?'pickup':s==='PICKED'?'deliver':s==='DELIVERING'?'complete':''}onLoad(load);onPullDownRefresh(load)
</script>
<template><view class="runner"><view class="tabs"><text :class="{active:tab==='available'}" @tap="tab='available';load()">待接配送</text><text :class="{active:tab==='mine'}" @tap="tab='mine';load()">我的配送</text></view><view v-if="loading" class="state">正在加载…</view><view v-else-if="!orders.length" class="state">{{tab==='available'?'暂无待取餐配送单':'暂无配送记录'}}</view><view v-else v-for="order in orders" :key="order.id" class="card"><view><text class="name">{{order.merchant?.name}}</text><text class="badge">{{text(order.status)}}</text></view><text>{{order.items.map((v:any)=>`${v.item_name}×${v.quantity}`).join('、')}}</text><text class="addr">送至：{{order.delivery_address}}</text><view class="foot"><text>收入 ¥{{Number(order.runner_income||order.delivery_fee).toFixed(2)}}</text><button v-if="tab==='available'" size="mini" @tap="doAction(order,'accept')">接单</button><button v-else-if="next(order.status)" size="mini" @tap="doAction(order,next(order.status))">{{next(order.status)==='pickup'?'确认取餐':next(order.status)==='deliver'?'开始配送':'确认送达'}}</button></view></view></view></template>
<style scoped lang="scss">.runner{min-height:100vh;padding:20rpx 22rpx;background:#f6f9f3}.tabs{display:flex;gap:42rpx;padding:10rpx 14rpx 22rpx;color:#75837a;font-size:28rpx}.tabs text.active{color:#259461;font-weight:800;border-bottom:5rpx solid #52c41a}.state{padding-top:150rpx;text-align:center;color:#849087}.card{display:grid;gap:16rpx;margin-bottom:18rpx;padding:25rpx;border-radius:24rpx;background:#fff;color:#55635b;font-size:24rpx}.card>view:first-child,.foot{display:flex;align-items:center;justify-content:space-between}.name{color:#26392f;font-size:30rpx;font-weight:750}.badge{padding:5rpx 10rpx;border-radius:9rpx;background:#e7f7ec;color:#2f9564;font-size:20rpx}.addr{color:#87928c;font-size:22rpx}.foot{padding-top:16rpx;border-top:1rpx solid #edf1ee;color:#e76843}.foot button{margin:0;border-radius:25rpx;background:#52c41a;color:#fff}</style>
