<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import UniIcons from '@dcloudio/uni-ui/lib/uni-icons/uni-icons.vue'
import { useAuthStore } from '@/stores/auth'
import { http, uploadImage } from '@/utils/request'
import { toAbsoluteFileUrl } from '@/utils/format'
const auth = useAuthStore(); const uploading = ref(false); const submitting = ref(false)
const form = reactive({ realName: '', studentId: '', phone: '', reason: '', cardImageUrl: '' })
const statusText = computed(() => auth.role === 'runner' ? '已是跑腿员' : ({ NONE: '未申请', PENDING: '审核中', APPROVED: '审核通过', REJECTED: '审核拒绝' }[auth.runnerAuthStatus] || '未申请'))
async function chooseCard() { if (uploading.value) return; uni.chooseImage({ count: 1, sourceType: ['album','camera'], success: async result => { uploading.value = true; try { form.cardImageUrl = await uploadImage(result.tempFilePaths[0]); uni.showToast({ title: '证件照片已上传', icon: 'success' }) } catch (error: any) { uni.showToast({ title: error.message || '上传失败', icon: 'none' }) } finally { uploading.value = false } } }) }
async function submit() { if (!form.realName.trim()) return uni.showToast({ title: '请输入真实姓名', icon: 'none' }); if (!form.studentId.trim()) return uni.showToast({ title: '请输入学号', icon: 'none' }); if (!/^1[3-9]\d{9}$/.test(form.phone.trim())) return uni.showToast({ title: '请输入正确手机号', icon: 'none' }); if (!form.cardImageUrl) return uni.showToast({ title: '请上传学生证或身份证照片', icon: 'none' }); if (submitting.value) return; submitting.value = true; try { await http.post('/user/auth', { real_name: form.realName.trim(), student_id: form.studentId.trim(), phone: form.phone.trim(), reason: form.reason.trim() || '申请成为校园跑腿员', card_image_url: form.cardImageUrl }); await auth.fetchRunnerAuth(); uni.showToast({ title: '申请已提交', icon: 'success' }) } catch (error: any) { uni.showToast({ title: error.message || '提交失败', icon: 'none' }) } finally { submitting.value = false } }
onLoad(async () => { await auth.bootstrap(); form.realName = auth.profile?.nickname || ''; form.studentId = auth.profile?.studentId || ''; form.phone = auth.profile?.phone || ''; await auth.fetchRunnerAuth() })
</script>
<template><view class="page-shell"><view class="card status-card"><view><view class="section-title">跑腿员资格</view><view class="section-desc">当前状态：{{ statusText }}</view></view><uni-icons type="auth-filled" size="34" color="#2563eb" /></view><view v-if="auth.role !== 'runner' && auth.runnerAuthStatus !== 'PENDING'" class="card form-card"><view class="field-label">真实姓名</view><input v-model="form.realName" class="input" placeholder="请输入真实姓名" /><view class="field-label">学号</view><input v-model="form.studentId" class="input" placeholder="请输入学号" /><view class="field-label">手机号</view><input v-model="form.phone" class="input" type="number" maxlength="11" placeholder="请输入11位手机号" /><view class="field-label">证件照片</view><view class="upload-card" @tap="chooseCard"><image v-if="form.cardImageUrl" class="card-image" :src="toAbsoluteFileUrl(form.cardImageUrl)" mode="aspectFill" /><template v-else><uni-icons type="camera-filled" size="34" color="#2563eb" /><text>{{ uploading ? '上传中...' : '上传学生证或身份证' }}</text><text class="hint">请保证姓名和证件信息清晰可见</text></template></view><view class="field-label">申请理由</view><textarea v-model="form.reason" class="textarea" maxlength="200" placeholder="请简单说明申请理由（选填）" /><view class="btn-primary submit" :class="{ disabled: submitting || uploading }" @tap="submit">{{ submitting ? '提交中...' : '提交申请' }}</view></view><view v-else class="card result-card">{{ auth.role === 'runner' ? '您已经是跑腿员，无需重复申请。' : '申请审核中，请耐心等待。' }}</view></view></template>
<style lang="scss" scoped>.status-card { display: flex; align-items: center; justify-content: space-between; }.form-card,.result-card { margin-top: 24rpx; }.field-label { margin: 24rpx 0 10rpx; }.field-label:first-child { margin-top: 0; }.upload-card { height: 300rpx; border: 2rpx dashed #93c5fd; border-radius: 18rpx; display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 12rpx; background: #eff6ff; color: #2563eb; }.card-image { width: 100%; height: 100%; border-radius: 16rpx; }.hint { font-size: 22rpx; color: #6b7280; }.submit { margin-top: 28rpx; }.result-card { text-align: center; color: #2563eb; }.disabled { opacity: .55; pointer-events: none; }</style>
