<script setup lang="ts">
import { reactive, ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import UniIcons from '@dcloudio/uni-ui/lib/uni-icons/uni-icons.vue'
import { useAuthStore } from '@/stores/auth'
import { http, uploadImage } from '@/utils/request'
import { toAbsoluteFileUrl } from '@/utils/format'
const auth=useAuthStore(),saving=ref(false)
const form=reactive({nickname:'',phone:'',studentId:'',birthDate:''})
function sync(){form.nickname=auth.profile?.nickname||'';form.phone=auth.profile?.phone||'';form.studentId=auth.profile?.studentId||'';form.birthDate=auth.profile?.birthDate?.slice(0,10)||''}
async function chooseBirthDate(event:any){const next=event.detail.value;if(auth.profile?.birthDate&&next!==auth.profile.birthDate.slice(0,10)){const result=await uni.showModal({title:'确认修改生日',content:'生日信息用于发放生日优惠券，请确认日期真实无误。',confirmColor:'#52C41A'});if(!result.confirm)return}form.birthDate=next}
async function chooseAvatar(){uni.chooseImage({count:1,success:async result=>{try{const avatar=await uploadImage(result.tempFilePaths[0],'file');await http.post('/user/avatar',{avatar});await auth.fetchProfile();uni.showToast({title:'头像已更新',icon:'success'})}catch(error:any){uni.showToast({title:error.message||'上传失败',icon:'none'})}}})}
async function save(){if(!form.nickname.trim())return uni.showToast({title:'请输入昵称',icon:'none'});if(!/^1[3-9]\d{9}$/.test(form.phone.trim()))return uni.showToast({title:'请输入正确的11位手机号',icon:'none'});if(saving.value)return;saving.value=true;try{await http.put('/user/profile',{nickname:form.nickname.trim(),phone:form.phone.trim(),student_id:form.studentId.trim(),birth_date:form.birthDate||null});await auth.fetchProfile();uni.showToast({title:'资料保存成功',icon:'success'})}catch(error:any){uni.showToast({title:error.message||'保存失败',icon:'none'})}finally{saving.value=false}}
onLoad(async()=>{await auth.bootstrap();if(!auth.profile)await auth.fetchProfile();sync()})
</script>
<template><view class="page-shell"><view class="card avatar-card" @tap="chooseAvatar"><image v-if="auth.profile?.avatar" class="avatar" :src="toAbsoluteFileUrl(auth.profile.avatar)" mode="aspectFill"/><view v-else class="avatar placeholder"><uni-icons type="person-filled" size="42" color="#fff"/></view><view class="avatar-copy"><view class="section-title">修改头像</view><view class="section-desc">选择清晰的个人头像</view></view><uni-icons type="camera-filled" size="24" color="#52C41A"/></view><view class="card form-card"><view class="field-label">昵称</view><input v-model="form.nickname" class="input" maxlength="20" placeholder="请输入昵称"/><view class="field-label">手机号</view><input v-model="form.phone" class="input" type="number" maxlength="11" placeholder="请输入11位手机号"/><view v-if="form.phone&&!/^1[3-9]\d{9}$/.test(form.phone)" class="error">手机号格式不正确</view><view class="field-label">学号</view><input v-model="form.studentId" class="input" maxlength="30" placeholder="请输入学号"/><view class="field-label">出生日期</view><picker mode="date" :value="form.birthDate" :end="new Date().toISOString().slice(0,10)" @change="chooseBirthDate"><view class="input birthday">{{form.birthDate||'补充生日信息'}}</view></picker><view class="birth-tip">生日信息用于自动发放生日优惠券</view><view class="btn-primary save" :class="{disabled:saving}" @tap="save">{{saving?'保存中...':'保存资料'}}</view></view></view></template>
<style lang="scss" scoped>.avatar-card{display:flex;align-items:center;gap:20rpx}.avatar{width:112rpx;height:112rpx;border-radius:50%}.placeholder{display:flex;align-items:center;justify-content:center;background:#52c41a}.avatar-copy{flex:1}.form-card{margin-top:24rpx}.field-label{margin:24rpx 0 10rpx}.field-label:first-child{margin-top:0}.error{margin-top:8rpx;color:#ef4444;font-size:22rpx}.birthday{display:flex;align-items:center;color:#389e0d}.birth-tip{margin-top:8rpx;color:#8a968b;font-size:21rpx}.save{margin-top:32rpx}.disabled{opacity:.55;pointer-events:none}</style>
