<script setup lang="ts">
import { computed, ref } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import { http } from '@/utils/request'
const tab=ref<'UNUSED'|'USED'|'EXPIRED'>('UNUSED'),loading=ref(false),rows=ref<any[]>([])
const tabs=[{key:'UNUSED',label:'未使用'},{key:'USED',label:'已使用'},{key:'EXPIRED',label:'已过期'}] as const
const list=computed(()=>rows.value.filter(v=>v.status===tab.value))
const money=(v:any)=>Number(v||0).toFixed(2)
const valueText=(c:any)=>c.type==='CASH'?`¥${money(c.value)}`:`${Number(c.value)}折`
const condition=(c:any)=>Number(c.min_order_amount)>0?`满¥${money(c.min_order_amount)}可用`:'无门槛'
async function load(){loading.value=true;try{const result=await http.get<any>('/coupons/my',{page:1,page_size:100});rows.value=(result?.data??result)?.list??[]}catch{rows.value=[]}finally{loading.value=false}}
function use(){uni.switchTab({url:'/pages/task/publish'})}
onShow(load)
</script>
<template><view class="page-shell coupon-page"><view class="page-head"><text class="page-title">我的优惠券</text><text class="page-desc">发布任务时可直接抵扣跑腿费用</text></view><view class="tabs"><view v-for="item in tabs" :key="item.key" :class="{active:tab===item.key}" @tap="tab=item.key">{{item.label}}</view></view><view v-if="loading" class="empty-box">加载中...</view><view v-else-if="!list.length" class="empty-box">这里还没有优惠券</view><view v-else class="coupon-list"><view v-for="item in list" :key="item.id" class="coupon-card" :class="{muted:item.status!=='UNUSED'}"><view class="coupon-value">{{valueText(item.coupon)}}</view><view class="coupon-info"><text class="coupon-name">{{item.coupon.name}}</text><text>{{condition(item.coupon)}}</text><text>有效期至 {{new Date(item.expired_at).toLocaleDateString('zh-CN')}}</text></view><button v-if="item.status==='UNUSED'" class="use-btn" @tap="use">去使用</button><text v-else class="status">{{item.status==='USED'?'已使用':'已过期'}}</text></view></view></view></template>
<style scoped>.coupon-page{min-height:100vh;background:#f6f9f3}.page-head{display:flex;flex-direction:column;gap:10rpx;margin-bottom:24rpx}.page-title{font-size:42rpx;font-weight:800;color:#293630}.page-desc{font-size:25rpx;color:#6f7d73}.tabs{display:grid;grid-template-columns:repeat(3,1fr);padding:8rpx;margin-bottom:24rpx;border-radius:24rpx;background:#fff}.tabs view{height:72rpx;display:flex;align-items:center;justify-content:center;border-radius:18rpx;color:#7a847f}.tabs .active{background:#f1faed;color:#389e0d;font-weight:700}.coupon-list{display:flex;flex-direction:column;gap:22rpx}.coupon-card{display:grid;grid-template-columns:150rpx 1fr auto;align-items:center;gap:22rpx;min-height:180rpx;padding:28rpx 24rpx;border-radius:30rpx;background:#fff;box-shadow:0 10rpx 30rpx rgba(36,69,51,.08)}.coupon-value{color:#52c41a;font-size:40rpx;font-weight:800;text-align:center}.coupon-info{display:flex;min-width:0;padding-left:22rpx;flex-direction:column;gap:9rpx;border-left:2rpx dashed #d9f7be;color:#768079;font-size:22rpx}.coupon-name{color:#293630;font-size:29rpx;font-weight:700}.use-btn{padding:0 22rpx;height:62rpx;border:0;border-radius:31rpx;background:#52c41a;color:#fff;font-size:23rpx}.status{color:#7b867e;font-size:23rpx}.muted{filter:grayscale(.72);opacity:.7}@media(max-width:360px){.coupon-card{grid-template-columns:120rpx 1fr}.use-btn,.status{grid-column:2}}</style>
