<script setup lang="ts">
import { computed, ref } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import { http } from '@/utils/request'

const tab=ref<'available'|'mine'>('available'),loading=ref(false),available=ref<any[]>([]),mine=ref<any[]>([])
const list=computed(()=>tab.value==='available'?available.value:mine.value)
const money=(v:any)=>Number(v||0).toFixed(2)
const valueText=(c:any)=>c.type==='CASH'?`¥${money(c.value)}`:`${Number(c.value)}%`
const condition=(c:any)=>Number(c.min_order_amount)>0?`满 ¥${money(c.min_order_amount)} 可用`:'无门槛'
const date=(v:string)=>new Date(v).toLocaleDateString('zh-CN')
async function load(){loading.value=true;try{const [a,m]=await Promise.all([http.get<any>('/coupons/available'),http.get<any>('/coupons/my',{page:1,page_size:100})]);available.value=a?.data??a??[];mine.value=(m?.data??m)?.list??[]}catch{available.value=[];mine.value=[]}finally{loading.value=false}}
async function receive(id:string){try{await http.post(`/coupons/receive/${id}`,{});uni.showToast({title:'领取成功',icon:'success'});await load()}catch(e:any){uni.showToast({title:e?.message||'领取失败',icon:'none'})}}
onShow(load)
</script>
<template><view class="page-shell coupon-page"><view class="page-head"><text class="page-title">优惠券中心</text><text class="page-desc">领取后可在发布任务时抵扣配送费</text></view><view class="tabs"><view :class="{active:tab==='available'}" @tap="tab='available'">可领取</view><view :class="{active:tab==='mine'}" @tap="tab='mine'">已领取</view></view><view v-if="loading" class="empty-box">加载中...</view><view v-else-if="!list.length" class="empty-box">暂无优惠券</view><view v-else class="coupon-list"><view v-for="item in list" :key="item.id" class="coupon-card" :class="{muted:tab==='mine'&&item.status!=='UNUSED'}"><view class="coupon-value">{{valueText(tab==='available'?item:item.coupon)}}</view><view class="coupon-info"><text class="coupon-name">{{(tab==='available'?item:item.coupon).name}}</text><text>{{condition(tab==='available'?item:item.coupon)}}</text><text>有效期至 {{date((tab==='available'?item:item.coupon).end_date)}}</text></view><view v-if="tab==='available'" class="receive-btn" :class="{disabled:!item.can_receive}" @tap="item.can_receive&&receive(item.id)">{{item.can_receive?'领取':'已达上限'}}</view><text v-else class="status">{{item.status==='UNUSED'?'可使用':item.status==='USED'?'已使用':'已过期'}}</text></view></view></view></template>
<style scoped>.coupon-page{background:#f6f9f3}.page-head{display:flex;flex-direction:column;gap:10rpx;margin-bottom:24rpx}.page-title{font-size:42rpx;font-weight:800;color:#293630}.page-desc{font-size:25rpx;color:#6f7d73}.tabs{display:grid;grid-template-columns:1fr 1fr;padding:8rpx;margin-bottom:24rpx;border-radius:24rpx;background:#fff}.tabs view{height:72rpx;display:flex;align-items:center;justify-content:center;border-radius:18rpx;color:#7a847f}.tabs .active{background:#f1faed;color:#389e0d;font-weight:700}.coupon-list{display:flex;flex-direction:column;gap:22rpx}.coupon-card{position:relative;display:grid;grid-template-columns:150rpx 1fr auto;align-items:center;gap:22rpx;min-height:180rpx;padding:28rpx 24rpx;border-radius:30rpx;background:#fff;box-shadow:0 10rpx 30rpx rgba(36,69,51,.08);overflow:hidden}.coupon-card:before,.coupon-card:after{content:'';position:absolute;left:137rpx;width:28rpx;height:28rpx;border-radius:50%;background:#f6f9f3}.coupon-card:before{top:-14rpx}.coupon-card:after{bottom:-14rpx}.coupon-value{color:#52c41a;font-size:40rpx;font-weight:800;text-align:center}.coupon-info{display:flex;min-width:0;padding-left:22rpx;flex-direction:column;gap:9rpx;border-left:2rpx dashed #d9f7be;color:#768079;font-size:22rpx}.coupon-name{color:#293630;font-size:29rpx;font-weight:700}.receive-btn{padding:14rpx 22rpx;border-radius:999rpx;background:#52c41a;color:#fff;font-size:23rpx}.receive-btn.disabled{background:#d4dbd1}.status{color:#6f7d73;font-size:24rpx;font-weight:600}.muted{filter:grayscale(.7);opacity:.68}@media(max-width:360px){.coupon-card{grid-template-columns:120rpx 1fr}.receive-btn,.status{grid-column:2}.coupon-card:before,.coupon-card:after{left:107rpx}}</style>
