<script setup lang="ts">
import { ref } from 'vue'
import { onLoad, onPullDownRefresh } from '@dcloudio/uni-app'
import { http } from '@/utils/request'

const id=ref(''),post=ref<any>(null),comments=ref<any[]>([]),loading=ref(false),comment=ref(''),sending=ref(false)
const payload=(v:any)=>v?.data?.data??v?.data??v??{}
const optionTime=(value:string)=>{const date=new Date(value);return Number.isNaN(date.getTime())?'刚刚':date.toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false})}
async function load(){loading.value=true;try{const data=payload(await http.get(`/forum/posts/${id.value}`));post.value=data.post;comments.value=Array.isArray(data.comments)?data.comments:[]}catch(error:any){uni.showToast({title:error?.message||'信息加载失败',icon:'none'})}finally{loading.value=false;uni.stopPullDownRefresh()}}
async function toggle(type:'like'|'favorite'){if(!post.value)return;const field=type==='like'?'is_liked':'is_favorited',count=type==='like'?'like_count':'favorite_count',enabled=!post.value[field];post.value[field]=enabled;post.value[count]=Math.max(0,Number(post.value[count]||0)+(enabled?1:-1));try{const data=payload(enabled?await http.post(`/forum/posts/${id.value}/${type}`):await http.delete(`/forum/posts/${id.value}/${type}`));post.value[count]=Number(data[`${type}_count`]??post.value[count])}catch(error:any){post.value[field]=!enabled;post.value[count]=Math.max(0,Number(post.value[count]||0)+(enabled?-1:1));uni.showToast({title:error?.message||'操作失败',icon:'none'})}}
async function sendComment(){if(!comment.value.trim())return;if(sending.value)return;sending.value=true;try{const data=payload(await http.post(`/forum/posts/${id.value}/comments`,{content:comment.value.trim()}));comments.value=[...comments.value,data.comment];comment.value='';if(post.value)post.value.comment_count=Number(post.value.comment_count||0)+1}catch(error:any){uni.showToast({title:error?.message||'评论失败',icon:'none'})}finally{sending.value=false}}
onLoad((query:any)=>{id.value=String(query.id||'');load()});onPullDownRefresh(load)
</script>

<template><view class="detail"><view v-if="loading&&!post" class="state">信息加载中…</view><template v-else-if="post"><view class="card"><view class="author"><view class="avatar">{{(post.author?.nickname||'同').slice(0,1)}}</view><view><text>{{post.author?.nickname||'校园同学'}}</text><text>{{optionTime(post.created_at)}}{{post.location_name?` · ${post.location_name}`:''}}</text></view></view><text class="tag">{{post.category?.name||'校园信息'}}</text><text class="title">{{post.title}}</text><text class="content">{{post.content}}</text><view v-if="post.images?.length" class="images"><image v-for="image in post.images" :key="image" :src="image" mode="widthFix"/></view><view class="actions"><text :class="{active:post.is_liked}" @tap="toggle('like')">♥ {{post.like_count}}</text><text @tap="toggle('favorite')">{{post.is_favorited?'★':'☆'}} {{post.favorite_count}}</text><text>◌ {{post.comment_count}}</text></view></view><view class="comment-card"><text class="heading">评论 {{comments.length}}</text><view v-if="!comments.length" class="empty">还没有评论，来聊聊吧</view><view v-for="item in comments" :key="item.id" class="comment"><view class="avatar small">{{(item.author?.nickname||'同').slice(0,1)}}</view><view><text class="name">{{item.author?.nickname||'校园同学'}}</text><text class="comment-content">{{item.content}}</text><text class="time">{{optionTime(item.created_at)}}</text></view></view></view><view class="comment-bar"><input v-model="comment" maxlength="300" placeholder="说点什么…" @confirm="sendComment"/><button :loading="sending" @tap="sendComment">发送</button></view></template></view></template>

<style scoped lang="scss">.detail{min-height:100vh;padding:22rpx 22rpx 122rpx;background:#f6f9f3;color:#293630}.state,.empty{padding:100rpx 0;text-align:center;color:#89958e}.card,.comment-card{display:grid;gap:18rpx;padding:26rpx;border-radius:24rpx;background:#fff}.author{display:flex;align-items:center;gap:12rpx}.avatar{display:flex;width:52rpx;height:52rpx;align-items:center;justify-content:center;border-radius:50%;background:#e2f3e6;color:#418d63;font-size:25rpx;font-weight:700}.avatar.small{width:42rpx;height:42rpx;font-size:21rpx}.author text{display:block;font-size:24rpx}.author text:last-child,.time{margin-top:4rpx;color:#98a39d;font-size:19rpx}.tag{justify-self:start;border-radius:10rpx;padding:6rpx 10rpx;background:#e9f7ed;color:#419163;font-size:19rpx}.title{font-size:35rpx;font-weight:800}.content{font-size:27rpx;line-height:1.7;white-space:pre-wrap}.images{display:grid;gap:12rpx}.images image{width:100%;border-radius:14rpx}.actions{display:flex;gap:34rpx;padding-top:12rpx;border-top:1rpx solid #edf1ee;color:#87948b;font-size:24rpx}.actions text.active{color:#e2685c;font-weight:700}.comment-card{margin-top:18rpx}.heading{font-size:29rpx;font-weight:750}.comment{display:flex;gap:12rpx;padding-top:16rpx;border-top:1rpx solid #edf1ee}.name,.comment-content{display:block}.name{font-size:23rpx;font-weight:700}.comment-content{margin-top:6rpx;font-size:24rpx;line-height:1.5}.comment-bar{position:fixed;right:0;bottom:0;left:0;display:flex;padding:16rpx 22rpx calc(16rpx + env(safe-area-inset-bottom));gap:14rpx;background:#fff;box-shadow:0 -4rpx 16rpx rgba(28,63,41,.07)}.comment-bar input{height:68rpx;flex:1;border-radius:34rpx;padding:0 22rpx;background:#f1f5f1;font-size:24rpx}.comment-bar button{margin:0;border-radius:34rpx;background:#52ad75;color:#fff;font-size:24rpx}</style>
