<script setup lang="ts">
import { computed, ref } from 'vue'
import { onLoad, onPullDownRefresh } from '@dcloudio/uni-app'
import { http } from '@/utils/request'

type Category = { id:number; code:string; name:string; icon?:string }
type Post = { id:number; title:string; content:string; images?:string[]; location_name?:string; created_at:string; is_pinned:boolean; author?:{nickname?:string;avatar?:string}; category?:Category; like_count:number; comment_count:number; favorite_count:number; is_liked:boolean }
const categories=ref<Category[]>([]),posts=ref<Post[]>([]),active=ref<number|undefined>(),sort=ref<'latest'|'hot'>('latest'),loading=ref(false),keyword=ref('')
const payload=(v:any)=>v?.data?.data??v?.data??v??{}
const visible=computed(()=>posts.value.filter(post=>!keyword.value.trim()||`${post.title}${post.content}${post.location_name||''}`.includes(keyword.value.trim())))
const formatTime=(value:string)=>{const date=new Date(value);return Number.isNaN(date.getTime())?'刚刚':date.toLocaleDateString('zh-CN',{month:'numeric',day:'numeric'})}
async function load(){loading.value=true;try{const [categoryResult,postResult]=await Promise.all([http.get('/forum/categories'),http.get('/forum/posts',{page:1,page_size:40,category_id:active.value,sort:sort.value})]);const categoryData=payload(categoryResult),postData=payload(postResult);categories.value=Array.isArray(categoryData.list)?categoryData.list:[];posts.value=Array.isArray(postData.list)?postData.list:[]}catch(error:any){uni.showToast({title:error?.message||'广场加载失败',icon:'none'})}finally{loading.value=false;uni.stopPullDownRefresh()}}
function selectCategory(id?:number){active.value=id;void load()}
function switchSort(next:'latest'|'hot'){sort.value=next;void load()}
function open(post:Post){uni.navigateTo({url:`/pages/forum/detail?id=${post.id}`})}
function publish(){uni.navigateTo({url:'/pages/forum/publish'})}
async function toggleLike(post:Post){const liked=!post.is_liked;post.is_liked=liked;post.like_count=Math.max(0,post.like_count+(liked?1:-1));try{const result=payload(liked?await http.post(`/forum/posts/${post.id}/like`):await http.delete(`/forum/posts/${post.id}/like`));post.like_count=Number(result.like_count??post.like_count)}catch(error:any){post.is_liked=!liked;post.like_count=Math.max(0,post.like_count+(liked?-1:1));uni.showToast({title:error?.message||'操作失败',icon:'none'})}}
onLoad(load);onPullDownRefresh(load)
</script>

<template><view class="square"><view class="hero"><view><text class="eyebrow">CAMPUS SQUARE</text><text class="title">校园信息广场</text><text class="sub">失物招领、二手交易与想说的话</text></view><button @tap="publish">发布信息</button></view><view class="toolbar"><view class="search"><uni-icons type="search" size="18" color="#849087"/><input v-model="keyword" placeholder="搜索物品、地点或关键词"/></view><view class="sort"><text :class="{active:sort==='latest'}" @tap="switchSort('latest')">最新</text><text :class="{active:sort==='hot'}" @tap="switchSort('hot')">热门</text></view></view><scroll-view scroll-x class="categories" :show-scrollbar="false"><view class="category-row"><text :class="{active:!active}" @tap="selectCategory()">全部</text><text v-for="category in categories" :key="category.id" :class="{active:active===category.id}" @tap="selectCategory(category.id)">{{category.icon||'◉'}} {{category.name}}</text></view></scroll-view><view v-if="loading" class="state">正在加载校园新鲜事…</view><view v-else-if="!visible.length" class="state"><text>还没有相关信息</text><button size="mini" @tap="publish">发布第一条</button></view><view v-else class="post-list"><view v-for="post in visible" :key="post.id" class="post" @tap="open(post)"><view class="post-top"><view class="author"><view class="avatar">{{(post.author?.nickname||'同').slice(0,1)}}</view><view><text>{{post.author?.nickname||'校园同学'}}</text><text>{{formatTime(post.created_at)}}{{post.location_name?` · ${post.location_name}`:''}}</text></view></view><text v-if="post.is_pinned" class="pinned">置顶</text></view><view class="tag">{{post.category?.icon||'◉'}} {{post.category?.name||'校园信息'}}</view><text class="post-title">{{post.title}}</text><text class="post-content">{{post.content}}</text><view v-if="post.images?.length" class="images"><image v-for="image in post.images.slice(0,3)" :key="image" :src="image" mode="aspectFill"/></view><view class="post-foot"><text :class="{liked:post.is_liked}" @tap.stop="toggleLike(post)">♥ {{post.like_count}}</text><text>◌ {{post.comment_count}}</text><text>☆ {{post.favorite_count}}</text><text>查看详情 ›</text></view></view></view></view></template>

<style scoped lang="scss">.square{min-height:100vh;padding:24rpx 22rpx 44rpx;background:#f6f9f3;color:#293630}.hero{display:flex;min-height:176rpx;padding:29rpx 28rpx;align-items:center;justify-content:space-between;border-radius:28rpx;background:linear-gradient(135deg,#276f49,#74bb83);color:#fff}.eyebrow,.title,.sub{display:block}.eyebrow{font-size:19rpx;letter-spacing:3rpx;opacity:.78}.title{margin-top:7rpx;font-size:39rpx;font-weight:800}.sub{margin-top:6rpx;font-size:22rpx;opacity:.9}.hero button{margin:0;border-radius:28rpx;background:#fff;color:#287047;font-size:22rpx}.toolbar{display:flex;gap:16rpx;margin:19rpx 0}.search{display:flex;height:70rpx;flex:1;padding:0 18rpx;align-items:center;gap:10rpx;border-radius:18rpx;background:#fff}.search input{min-width:0;flex:1;font-size:24rpx}.sort{display:flex;align-items:center;gap:14rpx;color:#7b8980;font-size:23rpx}.sort text.active{color:#267c50;font-weight:800}.categories{width:calc(100% + 44rpx);margin-left:-22rpx;white-space:nowrap}.category-row{display:inline-flex;gap:12rpx;padding:0 22rpx}.category-row text{padding:11rpx 17rpx;border:1rpx solid #dfe9e1;border-radius:22rpx;background:#fff;color:#68786e;font-size:22rpx}.category-row text.active{border-color:#4caa70;background:#e6f6eb;color:#287c50;font-weight:700}.state{display:flex;min-height:390rpx;align-items:center;justify-content:center;flex-direction:column;gap:20rpx;color:#849087}.state button{margin:0;border-radius:28rpx;background:#52ad75;color:#fff;font-size:23rpx}.post-list{display:grid;gap:16rpx;margin-top:20rpx}.post{padding:23rpx;border-radius:24rpx;background:#fff;box-shadow:0 6rpx 18rpx rgba(33,76,49,.05)}.post-top,.author,.post-foot{display:flex;align-items:center}.post-top{justify-content:space-between}.author{gap:11rpx}.avatar{display:flex;width:46rpx;height:46rpx;align-items:center;justify-content:center;border-radius:50%;background:#dff2e4;color:#388a61;font-size:23rpx;font-weight:700}.author text{display:block;font-size:23rpx}.author text:last-child{margin-top:3rpx;color:#95a199;font-size:19rpx}.pinned,.tag{display:inline-flex;border-radius:10rpx;padding:5rpx 10rpx;font-size:18rpx}.pinned{background:#fff0cf;color:#b07810}.tag{margin-top:18rpx;background:#e9f7ed;color:#3f9464}.post-title{display:block;margin-top:13rpx;color:#273a30;font-size:29rpx;font-weight:800}.post-content{display:-webkit-box;overflow:hidden;margin-top:8rpx;color:#64746b;font-size:24rpx;line-height:1.55;-webkit-box-orient:vertical;-webkit-line-clamp:2}.images{display:grid;grid-template-columns:repeat(3,1fr);gap:8rpx;margin-top:14rpx}.images image{width:100%;height:155rpx;border-radius:12rpx}.post-foot{gap:22rpx;margin-top:17rpx;color:#8a968f;font-size:20rpx}.post-foot text:last-child{margin-left:auto;color:#4b9b6d}.post-foot .liked{color:#e46f62;font-weight:700}</style>
