<script setup lang="ts">
import { onLoad } from '@dcloudio/uni-app'
import { ref } from 'vue'
import { http, uploadImage } from '@/utils/request'

type Category={id:number;name:string;icon?:string}
const categories=ref<Category[]>([]),categoryId=ref<number|undefined>(),title=ref(''),content=ref(''),location=ref(''),images=ref<string[]>([]),saving=ref(false)
const payload=(v:any)=>v?.data?.data??v?.data??v??{}
async function load(){try{const data=payload(await http.get('/forum/categories'));categories.value=Array.isArray(data.list)?data.list:[];categoryId.value=categories.value[0]?.id}catch(error:any){uni.showToast({title:error?.message||'分类加载失败',icon:'none'})}}
function chooseCategory(id:number){categoryId.value=id}
function chooseImages(){uni.chooseImage({count:Math.max(1,9-images.value.length),sizeType:['compressed'],success:(result)=>{images.value=[...images.value,...(result.tempFilePaths||[])].slice(0,9)}})}
function removeImage(index:number){images.value=images.value.filter((_,itemIndex)=>itemIndex!==index)}
async function submit(){if(!categoryId.value)return uni.showToast({title:'请选择信息分类',icon:'none'});if(title.value.trim().length<2)return uni.showToast({title:'标题至少 2 个字符',icon:'none'});if(content.value.trim().length<5)return uni.showToast({title:'正文至少 5 个字符',icon:'none'});if(saving.value)return;saving.value=true;try{const imageUrls=await Promise.all(images.value.map(image=>uploadImage(image)));await http.post('/forum/posts',{category_id:categoryId.value,title:title.value.trim(),content:content.value.trim(),images:imageUrls,location_name:location.value.trim()||undefined});uni.showToast({title:'已提交审核',icon:'success'});setTimeout(()=>uni.redirectTo({url:'/pages/forum/index'}),600)}catch(error:any){uni.showToast({title:error?.message||'发布失败',icon:'none'})}finally{saving.value=false}}
onLoad(load)
</script>

<template><view class="publish"><view class="notice"><text>发布后将进入审核；通过后才会在校园广场公开展示。</text></view><view class="form-card"><text class="label">信息分类</text><scroll-view scroll-x :show-scrollbar="false" class="categories"><view class="category-row"><text v-for="category in categories" :key="category.id" :class="{active:categoryId===category.id}" @tap="chooseCategory(category.id)">{{category.name}}</text></view></scroll-view><text class="label">标题</text><input v-model="title" maxlength="100" placeholder="一句话说清楚你要发布什么"/><text class="label">正文</text><textarea v-model="content" maxlength="2000" placeholder="补充物品特征、价格、交易方式或你想说的话"/><view class="location"><uni-icons type="location" size="17" color="#4a9b6d"/><input v-model="location" maxlength="120" placeholder="地点（选填），例如：图书馆一楼"/></view><text class="label">图片（选填，最多 9 张）</text><view class="images"><view v-for="(image,index) in images" :key="image" class="image"><image :src="image" mode="aspectFill"/><text @tap="removeImage(index)">×</text></view><view v-if="images.length<9" class="add-image" @tap="chooseImages"><text>＋</text><text>添加图片</text></view></view></view><button class="submit" :loading="saving" @tap="submit">提交审核</button></view></template>

<style scoped lang="scss">.publish{min-height:100vh;padding:22rpx;background:#f6f9f3;color:#293630}.notice{margin-bottom:18rpx;border-radius:18rpx;padding:18rpx 20rpx;background:#e8f7ed;color:#438662;font-size:22rpx;line-height:1.5}.form-card{display:grid;gap:14rpx;padding:25rpx;border-radius:24rpx;background:#fff}.label{margin-top:5rpx;color:#374b40;font-size:24rpx;font-weight:700}.categories{width:100%;white-space:nowrap}.category-row{display:inline-flex;gap:12rpx}.category-row text{padding:10rpx 14rpx;border-radius:16rpx;background:#f1f5f1;color:#6c7b71;font-size:22rpx}.category-row text.active{background:#e2f5e9;color:#287d51;font-weight:700}.form-card input,.form-card textarea{width:100%;border-bottom:1rpx solid #e7eee8;padding:14rpx 0;font-size:25rpx}.form-card textarea{height:240rpx;line-height:1.55}.location{display:flex;padding:13rpx 0;align-items:center;gap:10rpx;border-bottom:1rpx solid #e7eee8}.location input{border:0;padding:0}.images{display:flex;flex-wrap:wrap;gap:12rpx}.image,.add-image{position:relative;display:flex;width:154rpx;height:154rpx;align-items:center;justify-content:center;border-radius:14rpx;overflow:hidden}.image image{width:100%;height:100%}.image>text{position:absolute;top:4rpx;right:4rpx;display:flex;width:33rpx;height:33rpx;align-items:center;justify-content:center;border-radius:50%;background:rgba(27,45,34,.65);color:#fff;font-size:25rpx}.add-image{flex-direction:column;gap:5rpx;border:1rpx dashed #9bc7a9;background:#f5faf6;color:#579b70;font-size:20rpx}.add-image text:first-child{font-size:40rpx}.submit{margin-top:22rpx;border-radius:44rpx;background:#52ad75;color:#fff;font-size:28rpx}</style>
