<script setup lang="ts">
import { computed, ref } from 'vue'
import { http } from '@/utils/request'
const props=defineProps<{items:any[]}>(),emit=defineEmits<{close:[];claimed:[string]}>()
const current=ref(0),claiming=ref(false),claimed=ref(new Set<string>()),mascot='/static/task-hall-icons/mascot.svg'
const row=computed(()=>props.items[current.value])
const valueText=(item:any)=>item?.coupon?.type==='CASH'?`¥${Number(item.coupon.value).toFixed(0)}`:`${Number(item?.coupon?.value||0)}折`
const condition=(item:any)=>Number(item?.coupon?.min_order_amount)>0?`满¥${Number(item.coupon.min_order_amount).toFixed(2)}可用`:'无门槛使用'
async function claim(){if(!row.value||claiming.value||claimed.value.has(row.value.id))return;claiming.value=true;try{await http.post('/coupons/claim',{userCouponId:row.value.id});claimed.value.add(row.value.id);emit('claimed',row.value.id);uni.showToast({title:'领取成功',icon:'success'})}catch(e:any){uni.showToast({title:e?.message||'领取失败',icon:'none'})}finally{claiming.value=false}}
</script>
<template><view class="mask" @tap.self="emit('close')"><view class="modal"><view class="close" @tap="emit('close')"><uni-icons type="closeempty" size="22" color="#6b776d"/></view><image class="mascot" :src="mascot" mode="aspectFit"/><text class="eyebrow">校园跑腿送你一份小惊喜</text><swiper class="swiper" :current="current" @change="current=$event.detail.current"><swiper-item v-for="item in items" :key="item.id"><view class="slide"><text class="value">{{valueText(item)}}</text><text class="name">{{item.coupon.name}}</text><text class="condition">{{condition(item)}}</text><text class="date">领取后有效至 {{new Date(item.expired_at).toLocaleDateString('zh-CN')}}</text></view></swiper-item></swiper><view v-if="items.length>1" class="dots"><view v-for="(_,i) in items" :key="i" :class="{active:i===current}"/></view><button class="claim" :disabled="claiming||claimed.has(row?.id)" @tap="claim">{{claimed.has(row?.id)?'已领取':claiming?'领取中...':'立即领取'}}</button></view></view></template>
<style scoped>.mask{position:fixed;inset:0;z-index:9999;display:flex;padding:40rpx;align-items:center;justify-content:center;background:rgba(23,42,29,.45);backdrop-filter:blur(16rpx);animation:fade .3s ease}.modal{position:relative;width:100%;max-width:620rpx;padding:44rpx 38rpx 38rpx;border:1rpx solid rgba(255,255,255,.65);border-radius:48rpx;background:rgba(255,255,255,.94);box-shadow:0 36rpx 100rpx rgba(28,76,36,.28);box-sizing:border-box;animation:rise .3s ease}.close{position:absolute;right:24rpx;top:24rpx;z-index:2;width:58rpx;height:58rpx;display:flex;align-items:center;justify-content:center;border-radius:50%;background:#f2f7ef}.mascot{display:block;width:150rpx;height:128rpx;margin:-88rpx auto 8rpx}.eyebrow{display:block;color:#52c41a;font-size:24rpx;font-weight:700;text-align:center}.swiper{height:300rpx}.slide{display:flex;height:100%;align-items:center;justify-content:center;flex-direction:column}.value{color:#389e0d;font-size:94rpx;font-weight:900;line-height:1.05}.name{margin-top:10rpx;color:#263328;font-size:34rpx;font-weight:800}.condition,.date{margin-top:10rpx;color:#758078;font-size:23rpx}.dots{display:flex;height:24rpx;align-items:center;justify-content:center;gap:10rpx}.dots view{width:12rpx;height:12rpx;border-radius:50%;background:#d6dfd2}.dots .active{width:34rpx;border-radius:10rpx;background:#52c41a}.claim{height:92rpx;margin-top:22rpx;border:0;border-radius:46rpx;background:#52c41a;color:#fff;font-size:30rpx;font-weight:800;box-shadow:0 14rpx 30rpx rgba(82,196,26,.28)}.claim[disabled]{background:#a8d895;box-shadow:none}@keyframes fade{from{opacity:0}to{opacity:1}}@keyframes rise{from{opacity:0;transform:translateY(28rpx)}to{opacity:1;transform:none}}</style>
