<script setup lang="ts">
import { ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import UniIcons from '@dcloudio/uni-ui/lib/uni-icons/uni-icons.vue'
import { http } from '@/utils/request'
import { formatMoney } from '@/utils/format'
const wallet = ref({ balance: 0, frozen: 0 }); const amount = ref(''); const charging = ref(false)
async function load() { const result: any = await http.get('/wallet/info').catch(() => ({})); const root = result?.data ?? result; wallet.value = { balance: Number(root?.balance || 0), frozen: Number(root?.frozen || 0) } }
async function recharge() { const value = Number(amount.value); if (!value || value <= 0) return uni.showToast({ title: '请输入正确金额', icon: 'none' }); if (charging.value) return; charging.value = true; try { await http.post('/wallet/recharge', { amount: value }); amount.value = ''; await load(); uni.showToast({ title: '模拟充值成功', icon: 'success' }) } catch (error: any) { uni.showToast({ title: error.message || '充值失败', icon: 'none' }) } finally { charging.value = false } }
onLoad(load)
</script>
<template><view class="page-shell"><view class="wallet-card card"><view class="row-between"><view><view class="light">可用余额</view><view class="balance">{{ formatMoney(wallet.balance) }}</view></view><uni-icons type="wallet-filled" size="38" color="#fff" /></view><view class="frozen">冻结金额 {{ formatMoney(wallet.frozen) }}</view></view><view class="card recharge-card"><view class="section-title">模拟充值</view><view class="notice"><uni-icons type="info-filled" size="18" color="#d97706" /><text>仅用于校园项目演示，不会发起真实支付或扣款。</text></view><input v-model="amount" class="input" type="digit" placeholder="请输入充值金额" /><view class="quick"><view v-for="value in [10, 20, 50, 100]" :key="value" @tap="amount = String(value)">¥{{ value }}</view></view><view class="btn-primary" :class="{ disabled: charging }" @tap="recharge">{{ charging ? '处理中...' : '确认模拟充值' }}</view></view><view class="card log-entry" @tap="uni.navigateTo({ url: '/pages/wallet/logs' })"><uni-icons type="list" size="22" color="#2563eb" /><text>查看钱包流水</text><uni-icons type="right" size="18" color="#9ca3af" /></view></view></template>
<style lang="scss" scoped>.wallet-card { color: #fff; background: linear-gradient(135deg,#2563eb,#6366f1); }.light { opacity: .8; }.balance { margin-top: 10rpx; font-size: 64rpx; font-weight: 800; }.frozen { margin-top: 20rpx; opacity: .82; }.recharge-card,.log-entry { margin-top: 24rpx; }.notice { display: flex; gap: 10rpx; margin: 18rpx 0; padding: 18rpx; background: #fffbeb; color: #92400e; font-size: 24rpx; border-radius: 14rpx; }.quick { display: flex; gap: 12rpx; margin: 18rpx 0; }.quick view { flex: 1; padding: 14rpx 0; text-align: center; background: #eff6ff; color: #2563eb; border-radius: 12rpx; }.log-entry { display: flex; align-items: center; gap: 16rpx; }.log-entry text { flex: 1; }.disabled { opacity: .55; pointer-events: none; }</style>
